-- Tabla de configuración general para la tienda
CREATE TABLE IF NOT EXISTS configuracion_general (
    id INT AUTO_INCREMENT PRIMARY KEY,
    clave VARCHAR(64) NOT NULL UNIQUE,
    valor TEXT NOT NULL,
    descripcion VARCHAR(255) DEFAULT NULL,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Ejemplo de inserción de variables iniciales
INSERT INTO configuracion_general (clave, valor, descripcion) VALUES
('correo_corporativo', '', 'Correo usado para notificaciones'),
('smtp_host', '', 'Host SMTP para envío de correos'),
('smtp_user', '', 'Usuario SMTP'),
('smtp_pass', '', 'Contraseña SMTP'),
('smtp_port', '587', 'Puerto SMTP'),
('smtp_secure', 'tls', 'Tipo de seguridad SMTP'),
('nombre_prefijo', 'TIENDA', 'Texto superior del encabezado de la tienda'),
('nombre_tienda', 'TVirtualGaming', 'Nombre principal visible de la tienda'),
('logo_tienda', '', 'Ruta del logo visible en el encabezado'),
('facebook', '', 'URL de Facebook de la tienda'),
('instagram', '', 'URL de Instagram de la tienda'),
('whatsapp', '', 'Número o enlace de WhatsApp de la tienda'),
('mensaje_whatsapp', '', 'Mensaje predefinido para el botón flotante de WhatsApp'),
('whatsapp_channel', '', 'URL del canal de WhatsApp de la tienda'),
('ff_bank_posicion', '0', 'Posicion para la conexion al banco de Free Fire'),
('ff_bank_token', '', 'Token para la conexion al banco de Free Fire'),
('ff_bank_clave', '', 'Clave para la conexion al banco de Free Fire'),
('ff_api_usuario', '', 'Usuario para la API de Free Fire'),
('ff_api_clave', '', 'Clave para la API de Free Fire'),
('ff_api_tipo', 'recargaFreefire', 'Tipo para la API de Free Fire'),
('theme_bg_main', '#0A0F14', 'Color base del fondo general de la tienda'),
('theme_bg_alt', '#0E1722', 'Color usado en degradados y secciones secundarias'),
('theme_surface', '#111827', 'Color de tarjetas, paneles y modales'),
('theme_surface_alt', '#181F2A', 'Color alterno para cabecera, dropdowns y paneles internos'),
('theme_primary', '#22D3EE', 'Color principal del brillo, bordes y textos destacados'),
('theme_highlight', '#00FFF7', 'Color de realce para brillos y botones destacados'),
('theme_secondary', '#2DD4BF', 'Color secundario para degradados, hover y efectos'),
('theme_success', '#34D399', 'Color para acciones positivas y estados correctos'),
('theme_warning', '#F59E0B', 'Color para alertas y estados de revisión'),
('theme_danger', '#F87171', 'Color para cancelaciones, errores y alertas críticas'),
('theme_text', '#F8FAFC', 'Color principal del texto en la tienda'),
('theme_text_muted', '#CBD5E1', 'Color de textos secundarios, ayudas y descripciones'),
('theme_price_text', '#22D3EE', 'Color del monto principal en precios de juegos y paquetes'),
('theme_price_muted', '#94A3B8', 'Color del prefijo "Desde" y la moneda en precios de juegos y paquetes'),
('theme_border', '#164E63', 'Color base de bordes, separadores y contenedores'),
('theme_button_primary', '#22D3EE', 'Color principal para botones, acciones y llamadas principales'),
('theme_button_secondary', '#2DD4BF', 'Color secundario para degradados y hover de botones'),
('theme_button_surface', '#0E1722', 'Color base para botones oscuros, menú y tarjetas seleccionables'),
('theme_custom_bg_main', '#0A0F14', 'Copia editable: Color base del fondo general de la tienda'),
('theme_custom_bg_alt', '#0E1722', 'Copia editable: Color usado en degradados y secciones secundarias'),
('theme_custom_surface', '#111827', 'Copia editable: Color de tarjetas, paneles y modales'),
('theme_custom_surface_alt', '#181F2A', 'Copia editable: Color alterno para cabecera, dropdowns y paneles internos'),
('theme_custom_primary', '#22D3EE', 'Copia editable: Color principal del brillo, bordes y textos destacados'),
('theme_custom_highlight', '#00FFF7', 'Copia editable: Color de realce para brillos y botones destacados'),
('theme_custom_secondary', '#2DD4BF', 'Copia editable: Color secundario para degradados, hover y efectos'),
('theme_custom_success', '#34D399', 'Copia editable: Color para acciones positivas y estados correctos'),
('theme_custom_warning', '#F59E0B', 'Copia editable: Color para alertas y estados de revisión'),
('theme_custom_danger', '#F87171', 'Copia editable: Color para cancelaciones, errores y alertas críticas'),
('theme_custom_text', '#F8FAFC', 'Copia editable: Color principal del texto en la tienda'),
('theme_custom_text_muted', '#CBD5E1', 'Copia editable: Color de textos secundarios, ayudas y descripciones'),
('theme_custom_price_text', '#22D3EE', 'Copia editable: Color del monto principal en precios de juegos y paquetes'),
('theme_custom_price_muted', '#94A3B8', 'Copia editable: Color del prefijo "Desde" y la moneda en precios de juegos y paquetes'),
('theme_custom_border', '#164E63', 'Copia editable: Color base de bordes, separadores y contenedores'),
('theme_custom_button_primary', '#22D3EE', 'Copia editable: Color principal para botones, acciones y llamadas principales'),
('theme_custom_button_secondary', '#2DD4BF', 'Copia editable: Color secundario para degradados y hover de botones'),
('theme_custom_button_surface', '#0E1722', 'Copia editable: Color base para botones oscuros, menú y tarjetas seleccionables');
